import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="bg-campfire-night">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-campfire-night bg-5x animate-campfire-float min-h-screen text-main-base w-full scrollbar-hide`}>
        {children}
      </body>
    </html>
  )
}
